
package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoImplementationService", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:4789/ws/demo?wsdl")
public class DemoImplementationService
    extends Service
{

    private final static URL DEMOIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException DEMOIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName DEMOIMPLEMENTATIONSERVICE_QNAME = new QName("http://ws/", "DemoImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:4789/ws/demo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEMOIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        DEMOIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public DemoImplementationService() {
        super(__getWsdlLocation(), DEMOIMPLEMENTATIONSERVICE_QNAME);
    }

    public DemoImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public DemoImplementationService(URL wsdlLocation) {
        super(wsdlLocation, DEMOIMPLEMENTATIONSERVICE_QNAME);
    }

    public DemoImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public DemoImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Demo
     */
    @WebEndpoint(name = "DemoImplementationPort")
    public Demo getDemoImplementationPort() {
        return super.getPort(new QName("http://ws/", "DemoImplementationPort"), Demo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Demo
     */
    @WebEndpoint(name = "DemoImplementationPort")
    public Demo getDemoImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "DemoImplementationPort"), Demo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw DEMOIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return DEMOIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
